# This is a basic workflow to help you get started with Actions

name: SFDX Build

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Salesforce SFDX CLI Action
      # You may pin to the exact commit or the version.
      # uses: sfdx-actions/setup-sfdx@995ab395faa742df5acabb76fbdb6a5a7a5057d0
        uses: sfdx-actions/setup-sfdx@v1
        with:
          # Authorize a Salesforce org using an SFDX auth URL
          sfdx-auth-url: ${{ secrets.DEVHUB_URL }}

      ##############################################################################################
      ##############################################################################################
      #Sets the default devhub org for us to create scratch orgs and packages against
      - name: Set Defaul DevHub
        run:  sfdx force:config:set defaultdevhubusername=riccardo.rotatori@gmail.com
      
      #Creates a scratch org to test our code
      - name: Create Scratch Org
        run: sfdx force:org:create -a courseScratchOrg -d 1 -f config/project-scratch-def.json -s

      #Pushes all configurations to scratch org
      - name: Pushing source
        run:  sfdx force:source:push -f
      
      #Run all Apex Test in our scratch org (-w 30 ...aspettiamo il completamento per un max di 30minutes..dopodiche killiamo)
      - name: Running Apex Tests
        run:  sfdx force:apex:test:run -l RunLocalTests -w 30

      #Delet scratch org after successful build (-p no prompt to confirm deletion)
      - name: Deleting Scratch Org
        run:  sfdx force:org:delete -p
      ##############################################################################################
      ##############################################################################################

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
